export const FILTER_SELECT_UPDATE = 'FILTER_SELECT_UPDATE';
export const FILTER_INPUT_UPDATE = 'FILTER_INPUT_UPDATE';
export const LOADING_STATUS_UPDATE = 'LOADING_STATUS_UPDATE';
export const REQUEST_UPDATE = 'REQUEST_UPDATE';
export const OPEN_SURVIVOR_DETAILS = 'OPEN_SURVIVOR_DETAILS';
export const CLOSE_SURVIVOR_DETAILS = 'CLOSE_SURVIVOR_DETAILS';
